#if PLATFORM_ANDROID
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using Android.App;
using Android.Content;
using Android.OS;
using Android.Runtime;
using Serilog;

namespace VPNRouter.Core.Platform.Android;

// Earlier iterations defined a [Register]-annotated VpnRouterServiceRef
// here so we could write `typeof(VpnRouterServiceRef)` for Intent
// dispatch. Once VpnRouterService.cs landed in VPNRouter.Android with
// [Service(Name = "com.ninitux.vpnrouter.VpnRouterService")], that
// duplicate JNI class name caused a Mono GC-bridge abort on app startup
// ("asked if a class System.Object is a bridge before we inited
// java.lang.Object"). The fix: drop VpnRouterServiceRef entirely and
// let VPNRouter.Android pass the real Service Type via the public
// SetServiceType() entry point below.

/// <summary>
/// v3.0 Android Phase 1 (2026-04-30).
///
/// <para>Android-side equivalent of <see cref="VPNRouter.Core.Services.SingBoxManager"/>.
/// Where SingBoxManager spawns a real <c>sing-box.exe</c> process on
/// desktop, AndroidSingBoxRuntime sends Intents to the Android-native
/// <c>VpnRouterService</c> (Kotlin, in <c>VPNRouter.Android/VpnRouterService.kt</c>).
/// That service hosts the libbox.aar runtime in-process.</para>
///
/// <para>Intent contract (see <c>VpnRouterService.Companion</c>):</para>
/// <list type="bullet">
/// <item>Start: <c>ACTION_START</c> + <c>EXTRA_CONFIG_JSON</c> (string)
/// + <c>EXTRA_ALLOWED_PACKAGES</c> (string[]).</item>
/// <item>Stop: <c>ACTION_STOP</c>.</item>
/// </list>
///
/// <para>VpnService consent flow (must run BEFORE the first Start call):
/// MainActivity calls <c>Android.Net.VpnService.Prepare(this)</c>; if
/// non-null, present that Intent via <c>StartActivityForResult</c> and
/// only call into <c>Start</c> here from <c>OnActivityResult</c>.</para>
/// </summary>
public sealed class AndroidSingBoxRuntime
{
    private const string ActionStart = "com.ninitux.vpnrouter.START";
    private const string ActionStop = "com.ninitux.vpnrouter.STOP";
    private const string ExtraConfigJson = "config_json";
    private const string ExtraAllowedPackages = "allowed_packages";

    /// <summary>
    /// Clash API external_controller — same port the desktop side uses for
    /// hot-reload + health probes. libbox exposes this when the active
    /// config has an <c>experimental.clash_api</c> block, which our
    /// ConfigGenerator always emits.
    /// </summary>
    private const string ClashApiUrl = "http://127.0.0.1:9090/configs";

    /// <summary>
    /// P1 clash_api secret (2026-07-10): bearer token matching the generated
    /// config's <c>experimental.clash_api.secret</c>. Set by
    /// <c>AndroidConfigBuilder.ApplyClashApiSecret</c> on every config build
    /// (the single choke point every tunnel start flows through); without it
    /// <see cref="IsRunningAsync"/> 401s against the secret-locked libbox API
    /// and Android would read a healthy tunnel as down. r8 note: nothing
    /// currently instantiates this runtime — if a consumer appears that polls
    /// BEFORE the first config build (e.g. UI-process restart over a live
    /// tunnel), it must prime this from the app-private stored secret first.
    /// </summary>
    public static string? ClashApiSecret { get; set; }

    private static readonly HttpClient _http = new() { Timeout = TimeSpan.FromSeconds(2) };

    /// <summary>
    /// VPNRouter.Android registers its concrete Service type here at app
    /// startup, so this Core layer can build the dispatch Intent without
    /// taking a hard reference on VPNRouter.Android (which would require
    /// a circular ProjectReference).
    /// </summary>
    private static Type? _serviceType;

    public static void RegisterServiceType(Type serviceType) => _serviceType = serviceType;

    private readonly ILogger _logger;

    public AndroidSingBoxRuntime(ILogger logger)
    {
        _logger = logger;
    }

    /// <summary>
    /// Send an <c>ACTION_START</c> intent to VpnRouterService.
    /// </summary>
    /// <param name="configJson">Full sing-box config JSON, generated by
    /// <c>ConfigGenerator</c> with the PLATFORM_ANDROID branch (no
    /// <c>process_name</c> route rules — per-app routing happens at the
    /// OS layer via VpnService.Builder.addAllowedApplication).</param>
    /// <param name="allowedPackages">Android package IDs to route through
    /// the tunnel. Empty list = full-tunnel (everything routes).</param>
    public void Start(string configJson, IReadOnlyList<string> allowedPackages)
    {
        ArgumentNullException.ThrowIfNull(configJson);
        ArgumentNullException.ThrowIfNull(allowedPackages);

        var context = Application.Context
            ?? throw new InvalidOperationException(
                "Application.Context is null — AndroidSingBoxRuntime.Start called " +
                "before Avalonia attached to the Activity?");

        var pkgArray = new string[allowedPackages.Count];
        for (var i = 0; i < allowedPackages.Count; i++)
        {
            pkgArray[i] = allowedPackages[i];
        }

        var serviceType = _serviceType ?? throw new InvalidOperationException(
            "AndroidSingBoxRuntime.RegisterServiceType must be called before Start.");

        using var intent = new Intent(context, serviceType)
            .SetAction(ActionStart)
            .PutExtra(ExtraConfigJson, configJson)
            .PutExtra(ExtraAllowedPackages, pkgArray);

        // Android 8+ requires startForegroundService for Services that
        // call startForeground() within 5s — our VpnRouterService does
        // exactly that in onStartCommand to satisfy the API 26+ contract.
        if (Build.VERSION.SdkInt >= BuildVersionCodes.O)
        {
            context.StartForegroundService(intent);
        }
        else
        {
            context.StartService(intent);
        }

        _logger.Information(
            "[AndroidSingBoxRuntime] Start dispatched ({Pkgs} allowed packages, configJson {Bytes} bytes)",
            allowedPackages.Count,
            configJson.Length);
    }

    /// <summary>
    /// Send <c>ACTION_STOP</c> intent. Idempotent — calling when no tunnel
    /// is active is a no-op (the Service handles ACTION_STOP and stops
    /// itself even if it wasn't started yet).
    /// </summary>
    public void Stop()
    {
        var context = Application.Context;
        if (context is null)
        {
            // App tearing down — nothing to stop.
            return;
        }

        if (_serviceType is null)
        {
            return;
        }

        using var intent = new Intent(context, _serviceType)
            .SetAction(ActionStop);

        // For STOP we use plain StartService (even on API 26+) — the
        // Service is tearing itself down, so it doesn't need foreground
        // promotion.
        context.StartService(intent);

        _logger.Information("[AndroidSingBoxRuntime] Stop dispatched");
    }

    /// <summary>
    /// Async health probe via the Clash API endpoint that libbox exposes
    /// when active. Returns false on any error (libbox dead, port not
    /// bound, network unreachable).
    /// </summary>
    public async Task<bool> IsRunningAsync(CancellationToken ct = default)
    {
        try
        {
            using var req = new HttpRequestMessage(HttpMethod.Get, ClashApiUrl);
            if (!string.IsNullOrEmpty(ClashApiSecret))
                req.Headers.Authorization =
                    new System.Net.Http.Headers.AuthenticationHeaderValue("Bearer", ClashApiSecret);
            using var resp = await _http.SendAsync(req, ct).ConfigureAwait(false);
            return resp.IsSuccessStatusCode;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Sync wrapper for <see cref="IsRunningAsync"/>. Convenience for
    /// callers that can't await (UI health-check polling, etc.).
    /// </summary>
    public bool IsRunning()
    {
        try
        {
            return IsRunningAsync(CancellationToken.None).GetAwaiter().GetResult();
        }
        catch
        {
            return false;
        }
    }

    /// <summary>Health probe — same heuristic as IsRunning.</summary>
    public bool IsHealthy() => IsRunning();
}
#endif
