#!/usr/bin/env pwsh
# Compare desktop-elements.json vs android-elements.json per canonical page
# and emit a markdown report.
#
# Output: catalog/element-diff.md

$ErrorActionPreference = "Stop"
$here = $PSScriptRoot
$desktopJson = Join-Path $here "desktop-elements.json"
$androidJson = Join-Path $here "android-elements.json"
$out = Join-Path $here "element-diff.md"

$desk = Get-Content -Path $desktopJson -Raw | ConvertFrom-Json
$andr = Get-Content -Path $androidJson -Raw | ConvertFrom-Json

# Canonical page list = order from the parity audit plan
$pageOrder = @("Simple", "Subscribe", "Servers", "FreeConfigs", "Applications",
               "Network", "DpiBypass", "Telegram", "Tools", "AutoUpdate")

function Get-PageElements($cat, [string]$pageName) {
    foreach ($p in $cat.pages) {
        if ($p.page -eq $pageName) { return @($p.elements) }
    }
    return @()
}

function Get-Signature($el) {
    # Build a coarse signature for matching across platforms.
    # Prefer automation_name, then text/content, else name+type.
    $token = $null
    if ($el.automation_name) { $token = $el.automation_name }
    elseif ($el.text) { $token = $el.text }
    elseif ($el.name) { $token = $el.name }
    if (-not $token) { return $null }

    # Strip {Binding X} / {DynamicResource Y} into just the key
    if ($token -match '^\{Binding\s+([A-Za-z_][A-Za-z0-9_\.]*)') {
        $token = "binding:" + $Matches[1]
    } elseif ($token -match '^\{StaticResource\s+([A-Za-z_][A-Za-z0-9_\.]*)') {
        $token = "static:" + $Matches[1]
    } elseif ($token -match '^\{DynamicResource\s+([A-Za-z_][A-Za-z0-9_\.]*)') {
        $token = "dyn:" + $Matches[1]
    }
    return ($el.type + "::" + $token).ToLowerInvariant()
}

function Format-Element($el) {
    $token = ""
    if ($el.text) { $token = "text=`"" + $el.text + "`"" }
    elseif ($el.automation_name) { $token = "auto=`"" + $el.automation_name + "`"" }
    elseif ($el.name) { $token = "name=`"" + $el.name + "`"" }
    elseif ($el.command) { $token = "cmd=`"" + $el.command + "`"" }
    elseif ($el.classes) { $token = "class=`"" + $el.classes + "`"" }
    if (-not $token) { $token = "(unnamed)" }

    $loc = ""
    if ($el.line) { $loc = " L" + $el.line }
    if ($el.method) { $loc += " in " + $el.method + "()" }
    return "`"" + $el.type + "`" " + $token + $loc
}

$lines = @()
$lines += "# Desktop vs Android UI element diff"
$lines += ""
$lines += 'Generated by `parity-audit/catalog/diff-elements.ps1` on ' + (Get-Date).ToString("yyyy-MM-dd HH:mm")
$lines += ""
$lines += "**Method**: M8 (UI element catalog) -- XAML parsed via Select-Xml,"
$lines += 'Android parsed via regex over `new TypeName {...}` patterns. Approximate;'
$lines += "first pass surfaces structural divergences not subpixel layout."
$lines += ""
$lines += "**Inputs**:"
$lines += ""
$lines += "- desktop-elements.json -- " + ($desk.pages | Measure-Object -Property element_count -Sum).Sum + " elements across " + $desk.pages.Count + " pages"
$lines += "- android-elements.json -- " + ($andr.pages | Measure-Object -Property element_count -Sum).Sum + " elements across " + $andr.pages.Count + " pages"
$lines += ""

# ---- Per-page summary table ------------------------------------------------
$lines += "## Per-page element counts"
$lines += ""
$lines += "| Page | Desktop | Android | Delta |"
$lines += "|---|---:|---:|---:|"

$summary = @()
foreach ($p in $pageOrder) {
    $d = (Get-PageElements $desk $p).Count
    $a = (Get-PageElements $andr $p).Count
    $delta = $a - $d
    $deltaStr = if ($delta -ne 0) { "{0:+#;-#;0}" -f $delta } else { "0" }
    $summary += [PSCustomObject]@{Page=$p; Desktop=$d; Android=$a; Delta=$delta}
    $lines += "| $p | $d | $a | $deltaStr |"
}

$unkA = (Get-PageElements $andr "_Unknown_").Count
if ($unkA -gt 0) {
    $lines += "| _(Android shared helpers)_ | -- | $unkA | -- |"
}
$lines += ""

# ---- Per-page detail -------------------------------------------------------
$findingsCount = 0
foreach ($p in $pageOrder) {
    $deskEls = Get-PageElements $desk $p
    $andrEls = Get-PageElements $andr $p

    if ($deskEls.Count -eq 0 -and $andrEls.Count -eq 0) { continue }

    $lines += ""
    $lines += "## $p"
    $lines += ""

    # Type histograms
    $deskHist = $deskEls | Group-Object -Property type | Sort-Object Name | ForEach-Object { "$($_.Name)x$($_.Count)" }
    $andrHist = $andrEls | Group-Object -Property type | Sort-Object Name | ForEach-Object { "$($_.Name)x$($_.Count)" }
    $lines += "**Desktop types**: " + (($deskHist) -join ", ")
    $lines += ""
    $lines += "**Android types**: " + (($andrHist) -join ", ")
    $lines += ""

    # Build signature lookup
    $deskSig = @{}
    foreach ($e in $deskEls) {
        $s = Get-Signature $e
        if ($s) { $deskSig[$s] = $e }
    }
    $andrSig = @{}
    foreach ($e in $andrEls) {
        $s = Get-Signature $e
        if ($s) { $andrSig[$s] = $e }
    }

    # Elements only on Desktop (have a matchable signature, not in Android)
    $onlyDesk = @()
    foreach ($k in $deskSig.Keys) {
        if (-not $andrSig.ContainsKey($k)) { $onlyDesk += $deskSig[$k] }
    }
    $onlyAndr = @()
    foreach ($k in $andrSig.Keys) {
        if (-not $deskSig.ContainsKey($k)) { $onlyAndr += $andrSig[$k] }
    }

    # Filter to "interesting" only-on-X elements: drop anonymous Border/Grid/StackPanel
    # which are layout glue and produce noise.
    $boring = @("Border", "Grid", "StackPanel", "ScrollViewer", "Rectangle", "Ellipse")
    $onlyDesk = $onlyDesk | Where-Object {
        ($_.text -or $_.automation_name -or $_.name -or $_.command) -or ($boring -notcontains $_.type)
    }
    $onlyAndr = $onlyAndr | Where-Object {
        ($_.text -or $_.automation_name -or $_.name) -or ($boring -notcontains $_.type)
    }

    # Common signatures
    $bothCount = 0
    foreach ($k in $deskSig.Keys) {
        if ($andrSig.ContainsKey($k)) { $bothCount++ }
    }

    $lines += "**Common matched** (by name/text/automation): " + $bothCount
    $lines += ""

    if ($onlyDesk.Count -gt 0) {
        $lines += "**Only on Desktop** (" + $onlyDesk.Count + ")"
        $lines += ""
        foreach ($e in ($onlyDesk | Select-Object -First 20)) {
            $lines += "- " + (Format-Element $e)
        }
        if ($onlyDesk.Count -gt 20) {
            $lines += "- _... and " + ($onlyDesk.Count - 20) + " more_"
        }
        $lines += ""
        $findingsCount++
    }

    if ($onlyAndr.Count -gt 0) {
        $lines += "**Only on Android** (" + $onlyAndr.Count + ")"
        $lines += ""
        foreach ($e in ($onlyAndr | Select-Object -First 20)) {
            $lines += "- " + (Format-Element $e)
        }
        if ($onlyAndr.Count -gt 20) {
            $lines += "- _... and " + ($onlyAndr.Count - 20) + " more_"
        }
        $lines += ""
        $findingsCount++
    }

    if ($onlyDesk.Count -eq 0 -and $onlyAndr.Count -eq 0) {
        $lines += "_No identifiable element-level divergence by name/automation/text._"
        $lines += ""
    }
}

# ---- Footer ----------------------------------------------------------------
$lines += ""
$lines += "## Caveats"
$lines += ""
$lines += '1. **Signature matching is coarse**: matches by `type::token` where token'
$lines += '   is the visible text or `{Binding L_X}` localization key. An element'
$lines += "   with literal text on one platform and a binding on the other will"
$lines += "   show as divergent even if the rendered string is identical."
$lines += "2. **Layout containers** (Border/Grid/StackPanel without a name or text)"
$lines += "   are filtered out of the only-on-X lists to reduce noise. The summary"
$lines += "   table still counts them."
$lines += '3. **Android `_Unknown_` bucket** holds elements created in shared helper'
$lines += '   methods (e.g. `WrapSection`, `BuildProfileChip` reused across overlays).'
$lines += '   Manually inspect `android-elements.json` if a page count looks low.'
$lines += "4. **Telegram is desktop-only by design** (Win-only Telegram WebSocket"
$lines += "   proxy) -- divergence here is expected, not a finding."
$lines += "5. **AutoUpdate banner is Android-only** (Win uses Squirrel installer"
$lines += "   notify) -- divergence here is expected."

$content = $lines -join "`r`n"
Set-Content -Path $out -Value $content -Encoding utf8
Write-Host "Wrote $out"
Write-Host "  pages compared = $($pageOrder.Count)"
Write-Host "  divergence sections found = $findingsCount"
