using System.Reflection;
using VPNRouter.App.Localization;

namespace VPNRouter.App.ViewModels;

/// <summary>
/// v2.25.12 — PropertyChanged-aware proxies for every Strings.cs key used
/// in XAML. Each <c>L_Foo</c> returns <c>Strings.Foo</c>. When the user
/// toggles language, <see cref="RefreshL10nProxies"/> fires PropertyChanged
/// for every L_* member so bindings re-read the value. This replaces the
/// v2.17.10 workaround of rebuilding the entire MainWindow (which blocked
/// the UI thread for the whole XAML re-parse — ~200-500 ms of visible
/// freeze even after the v2.25.11 Dispatcher-defer fix).
///
/// Generated from <c>/tmp/gen-l10n.sh</c>; regenerate if Strings.cs adds
/// new keys that XAML starts referencing.
/// </summary>
public partial class MainWindowViewModel
{
    public string L_AboutBrandName => Strings.AboutBrandName;
    public string L_AboutCloseBtn => Strings.AboutCloseBtn;
    public string L_AboutCreatorLabel => Strings.AboutCreatorLabel;
    public string L_AboutRepoLabel => Strings.AboutRepoLabel;
    public string L_AboutSingBoxLabel => Strings.AboutSingBoxLabel;
    public string L_AboutTagline => Strings.AboutTagline;
    public string L_AboutTitle => Strings.AboutTitle;
    public string L_AboutVersionLabel => Strings.AboutVersionLabel;
    public string L_AddAppHint => Strings.AddAppHint;
    public string L_AddCategory => Strings.AddCategory;
    public string L_AddConfig => Strings.AddConfig;
    public string L_AddCustomAppHint => Strings.AddCustomAppHint;
    public string L_AddServerFirst => Strings.AddServerFirst;
    public string L_AddServers => Strings.AddServers;
    public string L_AddSubscription => Strings.AddSubscription;
    public string L_Apply => Strings.Apply;
    public string L_ApplyChanges => Strings.ApplyChanges;
    public string L_ApplyFailed => Strings.ApplyFailed;
    public string L_ApplyNowHint => Strings.ApplyNowHint;
    public string L_ApplyNowReloadVpn => Strings.ApplyNowReloadVpn;
    public string L_AppsGroupEmpty => Strings.AppsGroupEmpty;
    public string L_AppsHint => Strings.AppsHint;
    // v2.29.0 — Apps page full-tunnel banner (replaces silent IsEnabled
    // disable, see ApplicationsPage.axaml).
    public string L_AppsFullTunnelBanner => Strings.AppsFullTunnelBanner;
    public string L_AppsFullTunnelBannerAction => Strings.AppsFullTunnelBannerAction;
    // v2.30.0 — Custom rules engine (direct/proxy/block).
    public string L_CustomRulesTitle => Strings.CustomRulesTitle;
    public string L_CustomRulesDescription => Strings.CustomRulesDescription;
    public string L_CustomRulesPlaceholder => Strings.CustomRulesPlaceholder;
    public string L_CustomRulesErrorHeader => Strings.CustomRulesErrorHeader;
    public string L_CustomRulesConflictHeader => Strings.CustomRulesConflictHeader;
    // v2.30.0-r2 — Network → Rules section strings.
    public string L_CustomRulesPageDescription => Strings.CustomRulesPageDescription;
    public string L_CustomRulesEmpty => Strings.CustomRulesEmpty;
    public string L_CustomRulesAddTitle => Strings.CustomRulesAddTitle;
    public string L_CustomRulesAddBtn => Strings.CustomRulesAddBtn;
    public string L_CustomRulesActionLabel => Strings.CustomRulesActionLabel;
    public string L_CustomRulesTypeLabel => Strings.CustomRulesTypeLabel;
    public string L_CustomRulesValueLabel => Strings.CustomRulesValueLabel;
    public string L_CustomRulesCommentLabel => Strings.CustomRulesCommentLabel;
    public string L_CustomRulesValuePlaceholder => Strings.CustomRulesValuePlaceholder;
    public string L_CustomRulesAdvancedMode => Strings.CustomRulesAdvancedMode;
    public string L_CustomRulesValidationFailed => Strings.CustomRulesValidationFailed;
    public string L_CustomRulesDelete => Strings.CustomRulesDelete;
    public string L_CustomRulesEdit => Strings.CustomRulesEdit;
    public string L_CustomRulesMoveUp => Strings.CustomRulesMoveUp;
    public string L_CustomRulesMoveDown => Strings.CustomRulesMoveDown;
    public string LblSettingsRules => Strings.SectionRules;
    // Legacy v2.29.0 aliases (kept for cached XAML).
    public string L_CustomDirectRulesTitle => L_CustomRulesTitle;
    public string L_CustomDirectRulesDescription => L_CustomRulesDescription;
    public string L_CustomDirectRulesPlaceholder => L_CustomRulesPlaceholder;
    public string L_CustomDirectRulesErrorHeader => L_CustomRulesErrorHeader;
    public string L_AutoUpdateCheckLabel => Strings.AutoUpdateCheckLabel;
    public string L_AutostartPlatformNotice => Strings.AutostartPlatformNotice;
    public string L_AutostartSection => Strings.AutostartSection;
    public string L_AutostartTgProxy => Strings.AutostartTgProxy;
    public string L_AutostartUi => Strings.AutostartUi;
    public string L_AutostartUiSessionHeader => Strings.AutostartUiSessionHeader;
    public string L_AutostartVpn => Strings.AutostartVpn;
    public string L_AutostartWithWindows => Strings.AutostartWithWindows;
    public string L_AutostartZapret => Strings.AutostartZapret;
    // v2.27 Bug C — two-section layout headers + hints
    public string L_AutostartBootSectionTitle => Strings.AutostartBootSectionTitle;
    public string L_AutostartBootSectionSub => Strings.AutostartBootSectionSub;
    public string L_AutostartComponentsInfoHint => Strings.AutostartComponentsInfoHint;
    public string L_AutostartLoginSectionTitle => Strings.AutostartLoginSectionTitle;
    public string L_AutostartLoginAppDescription => Strings.AutostartLoginAppDescription;
    // v2.27 §4.5 — prominent PID line replacing the small pill
    public string L_ServiceStoppedLine => Strings.ServiceStoppedLine;
    public string L_ServiceRunningLine =>
        ServiceVm.ServicePid.HasValue ? Strings.ServiceRunningLine(ServiceVm.ServicePid.Value) : Strings.ServiceRunningText;
    // v2.27.0-r2 — Simple autostart link-card replacing the old checkbox
    public string L_SmpAutostartCardTitle => Strings.SmpAutostartCardTitle;
    public string L_SmpAutostartCardStatus =>
        ServiceVm.IsInstalled && ServiceVm.IsRunning
            ? Strings.SmpAutostartCardOn
            : Strings.SmpAutostartCardOff;
    public string L_BtnAdd => Strings.BtnAdd;
    public string L_BypassRussianTrafficHint => Strings.BypassRussianTrafficHint;
    public string L_BypassRussianTrafficLabel => Strings.BypassRussianTrafficLabel;
    public string L_CategoryNamePrompt => Strings.CategoryNamePrompt;
    public string L_ChangesApplied => Strings.ChangesApplied;
    public string L_ChannelExperimental => Strings.ChannelExperimental;
    public string L_ChannelStable => Strings.ChannelStable;
    public string L_CheckFailed => Strings.CheckFailed;
    public string L_CheckForUpdates => Strings.CheckForUpdates;
    public string L_CheckLeaks => Strings.CheckLeaks;
    public string L_Checking => Strings.Checking;
    public string L_ClearDiscordCache => Strings.ClearDiscordCache;
    public string L_ColIp => Strings.ColIp;
    public string L_ColName => Strings.ColName;
    public string L_ColPing => Strings.ColPing;
    public string L_ColPort => Strings.ColPort;
    public string L_ColSecurity => Strings.ColSecurity;
    public string L_ColServer => Strings.ColServer;
    public string L_CustomAppLabel => Strings.CustomAppLabel;
    public string L_CustomConfigJson => Strings.CustomConfigJson;
    public string L_DoubleClickActiveConfig => Strings.DoubleClickActiveConfig;
    public string L_DoubleClickEditServer => Strings.DoubleClickEditServer;
    public string L_EnableWholeGroup => Strings.EnableWholeGroup;
    public string L_FailedStartVpn => Strings.FailedStartVpn;
    public string L_FcAdvancedSettings => Strings.FcAdvancedSettings;
    public string L_FcApplySelected => Strings.FcApplySelected;
    public string L_FcBandwidthHint => Strings.FcBandwidthHint;
    public string L_FcCancel => Strings.FcCancel;
    public string L_FcCleanupHint => Strings.FcCleanupHint;
    public string L_FcClearAll => Strings.FcClearAll;
    public string L_FcClearFailed => Strings.FcClearFailed;
    public string L_FcColBandwidth => Strings.FcColBandwidth;
    public string L_FcColCountry => Strings.FcColCountry;
    public string L_FcColEndpoint => Strings.FcColEndpoint;
    public string L_FcColLatency => Strings.FcColLatency;
    public string L_FcColSni => Strings.FcColSni;
    public string L_FcColTransport => Strings.FcColTransport;
    public string L_FcConfigsWord => Strings.FcConfigsWord;
    public string L_FcConnectHint => Strings.FcConnectHint;
    public string L_FcCountryAll => Strings.FcCountryAll;
    public string L_FcCountryFilter => Strings.FcCountryFilter;
    public string L_FcCustomBw => Strings.FcCustomBw;
    public string L_FcCustomPing => Strings.FcCustomPing;
    public string L_FcDashboardFake => Strings.FcDashboardFake;
    public string L_FcDashboardTimeout => Strings.FcDashboardTimeout;
    public string L_FcDashboardTlsFail => Strings.FcDashboardTlsFail;
    public string L_FcDashboardTotal => Strings.FcDashboardTotal;
    public string L_FcDashboardUnreach => Strings.FcDashboardUnreach;
    public string L_FcDashboardVerified => Strings.FcDashboardVerified;
    public string L_FcDashboardWorking => Strings.FcDashboardWorking;
    public string L_FcDeepExcludeRu => Strings.FcDeepExcludeRu;
    public string L_FcDeepHint => Strings.FcDeepHint;
    public string L_FcDeepStop => Strings.FcDeepStop;
    public string L_FcDeepStopTooltip => Strings.FcDeepStopTooltip;
    public string L_FcDeepTargetLabel => Strings.FcDeepTargetLabel;
    public string L_FcDeepVerify => Strings.FcDeepVerify;
    public string L_FcDeepVerifyTooltip => Strings.FcDeepVerifyTooltip;
    public string L_FcEmptyCtaButton => Strings.FcEmptyCtaButton;
    public string L_FcEmptyCtaSubtitle => Strings.FcEmptyCtaSubtitle;
    public string L_FcEmptyCtaTitle => Strings.FcEmptyCtaTitle;
    public string L_FcEmptyHint => Strings.FcEmptyHint;
    public string L_FcFastScanHint => Strings.FcFastScanHint;
    public string L_FcFastScanLabel => Strings.FcFastScanLabel;
    public string L_FcFilteredEmpty => Strings.FcFilteredEmpty;
    public string L_FcKeepVerified => Strings.FcKeepVerified;
    public string L_FcKeepVerifiedOnly => Strings.FcKeepVerifiedOnly;
    public string L_FcListHeader => Strings.FcListHeader;
    public string L_FcListShown => Strings.FcListShown;
    public string L_FcMbpsUnit => Strings.FcMbpsUnit;
    public string L_FcMoreOptions => Strings.FcMoreOptions;
    public string L_FcMsUnit => Strings.FcMsUnit;
    public string L_FcOpenLogs => Strings.FcOpenLogs;
    public string L_FcPageDescription => Strings.FcPageDescription;
    public string L_FcPresetBest => Strings.FcPresetBest;
    public string L_FcPresetChat => Strings.FcPresetChat;
    public string L_FcPresetCustom => Strings.FcPresetCustom;
    public string L_FcPresetGaming => Strings.FcPresetGaming;
    public string L_FcPresetLabel => Strings.FcPresetLabel;
    public string L_FcPresetStream => Strings.FcPresetStream;
    public string L_FcRefreshHint => Strings.FcRefreshHint;
    public string L_FcRefreshSources => Strings.FcRefreshSources;
    public string L_FcRefreshTooltip => Strings.FcRefreshTooltip;
    public string L_FcRetestAll => Strings.FcRetestAll;
    public string L_FcRetestTooltip => Strings.FcRetestTooltip;
    public string L_FcSecWarnBody => Strings.FcSecWarnBody;
    public string L_FcSecWarnCancel => Strings.FcSecWarnCancel;
    public string L_FcSecWarnDontUseList => Strings.FcSecWarnDontUseList;
    public string L_FcSecWarnGoodFor => Strings.FcSecWarnGoodFor;
    public string L_FcSecWarnHeader => Strings.FcSecWarnHeader;
    public string L_FcSecWarnProceed => Strings.FcSecWarnProceed;
    public string L_FcSecWarnTitle => Strings.FcSecWarnTitle;
    public string L_FcSmartRefreshHint => Strings.FcSmartRefreshHint;
    public string L_FcSmartRefreshLabel => Strings.FcSmartRefreshLabel;
    public string L_FcStatusApplyFailed => Strings.FcStatusApplyFailed;
    public string L_FcStatusCancelled => Strings.FcStatusCancelled;
    public string L_FcStatusEmpty => Strings.FcStatusEmpty;
    public string L_FcStatusMainVpnActive => Strings.FcStatusMainVpnActive;
    public string L_FcStatusNoDeepCandidates => Strings.FcStatusNoDeepCandidates;

    // ── v2.28.6 Phase 2 — Saved-tab strings ──
    public string L_FcTabSearch              => Strings.FcTabSearch;
    public string L_FcTabSaved               => Strings.FcTabSaved;
    public string L_FcSavedTabHint           => Strings.FcSavedTabHint;
    public string L_FcSavedRecheckAllBtn     => Strings.FcSavedRecheckAllBtn;
    public string L_FcSavedClearAllBtn       => Strings.FcSavedClearAllBtn;
    public string L_FcSavedColStatus         => Strings.FcSavedColStatus;
    public string L_FcSavedEmpty             => Strings.FcSavedEmpty;
    public string L_FcSavedRecheckOneTooltip => Strings.FcSavedRecheckOneTooltip;
    public string L_FcSavedRemoveOneTooltip  => Strings.FcSavedRemoveOneTooltip;
    public string L_FcSearchListEmptyHint    => Strings.FcSearchListEmptyHint;
    public string L_FcTargetNLabel => Strings.FcTargetNLabel;
    public string L_FcTipVpnActive => Strings.FcTipVpnActive;
    public string L_FcUserSrcAdd => Strings.FcUserSrcAdd;
    public string L_FcUserSrcAdded => Strings.FcUserSrcAdded;
    public string L_FcUserSrcDuplicate => Strings.FcUserSrcDuplicate;
    public string L_FcUserSrcEmpty => Strings.FcUserSrcEmpty;
    public string L_FcUserSrcEmptyUrl => Strings.FcUserSrcEmptyUrl;
    public string L_FcUserSrcHint => Strings.FcUserSrcHint;
    public string L_FcUserSrcInvalidUrl => Strings.FcUserSrcInvalidUrl;
    public string L_FcUserSrcNamePlaceholder => Strings.FcUserSrcNamePlaceholder;
    public string L_FcUserSrcRemoved => Strings.FcUserSrcRemoved;
    public string L_FcUserSrcSection => Strings.FcUserSrcSection;
    public string L_FcUserSrcUrlPlaceholder => Strings.FcUserSrcUrlPlaceholder;
    public string L_FcWithPingUnder => Strings.FcWithPingUnder;
    public string L_FieldName => Strings.FieldName;
    public string L_FieldPort => Strings.FieldPort;
    public string L_FieldPublicKey => Strings.FieldPublicKey;
    public string L_FieldServer => Strings.FieldServer;
    public string L_FieldShortId => Strings.FieldShortId;
    public string L_FieldUuid => Strings.FieldUuid;
    public string L_FlushDnsLabel => Strings.FlushDnsLabel;
    public string L_ForceIpv4Label => Strings.ForceIpv4Label;
    public string L_FullTunnel => Strings.FullTunnel;
    public string L_FullTunnelSubtitle => Strings.FullTunnelSubtitle;
    public string L_FullTunnelTitle => Strings.FullTunnelTitle;
    public string L_GameFilter => Strings.GameFilter;
    public string L_GameFilterAll => Strings.GameFilterAll;
    public string L_GameFilterOff => Strings.GameFilterOff;
    public string L_GameFilterTcp => Strings.GameFilterTcp;
    public string L_GameFilterUdp => Strings.GameFilterUdp;
    public string L_InstallingService => Strings.InstallingService;
    public string L_InvalidConfig => Strings.InvalidConfig;
    public string L_IpSetAny => Strings.IpSetAny;
    public string L_IpSetFilter => Strings.IpSetFilter;
    public string L_IpSetLoaded => Strings.IpSetLoaded;
    public string L_IpSetNone => Strings.IpSetNone;
    public string L_LanguageSwitching => Strings.LanguageSwitching;
    public string L_LblAddSubscriptionHint => Strings.LblAddSubscriptionHint;
    public string L_LblCustomBadge => Strings.LblCustomBadge;
    public string L_LblName => Strings.LblName;
    public string L_LblNoServers => Strings.LblNoServers;
    public string L_LblPort => Strings.LblPort;
    public string L_LblPublicKey => Strings.LblPublicKey;
    public string L_LblRoutingMode => Strings.LblRoutingMode;
    public string L_LblServer => Strings.LblServer;
    public string L_LblShortId => Strings.LblShortId;
    public string L_LblUuid => Strings.LblUuid;
    public string L_ModeCustomConfig => Strings.ModeCustomConfig;
    public string L_ModeManual => Strings.ModeManual;
    public string L_ModeSubscribe => Strings.ModeSubscribe;
    public string L_NeverRefreshed => Strings.NeverRefreshed;
    public string L_NotConnected => Strings.NotConnected;
    public string L_OpenFolder => Strings.OpenFolder;
    public string L_OpenGitHub => Strings.OpenGitHub;
    public string L_OpenServiceMenu => Strings.OpenServiceMenu;
    public string L_PasteVlessUri => Strings.PasteVlessUri;
    public string L_RefreshAll => Strings.RefreshAll;
    public string L_ReinstallService => Strings.ReinstallService;
    public string L_Remove => Strings.Remove;
    public string L_RemoveChecked => Strings.RemoveChecked;
    public string L_RemoveServiceLabel => Strings.RemoveServiceLabel;
    public string L_RemovingService => Strings.RemovingService;
    public string L_RestartService => Strings.RestartService;
    public string L_RoutingDescription => Strings.RoutingDescription;
    public string L_RunDiagnostics => Strings.RunDiagnostics;
    public string L_RunTestsLabel => Strings.RunTestsLabel;
    public string L_SectionContent => Strings.SectionContent;
    public string L_SectionLeakProtection => Strings.SectionLeakProtection;
    public string L_SectionRouting => Strings.SectionRouting;
    public string L_SectionUpdates => Strings.SectionUpdates;
    public string L_SelectCategoryHint => Strings.SelectCategoryHint;
    public string L_SelectSingBoxConfig => Strings.SelectSingBoxConfig;
    public string L_ServerListHint => Strings.ServerListHint;
    public string L_ServiceComponentsDisabledHint => Strings.ServiceComponentsDisabledHint;
    public string L_ServiceComponentsHeader => Strings.ServiceComponentsHeader;
    public string L_ServiceEnableLabel => Strings.ServiceEnableLabel;
    public string L_ServiceInstalledText => Strings.ServiceInstalledText;
    public string L_ServiceInstalling => Strings.ServiceInstalling;
    public string L_ServiceMasterSubtitle => Strings.ServiceMasterSubtitle;
    public string L_ServiceMasterTitle => Strings.ServiceMasterTitle;
    public string L_ServiceNotInstalledText => Strings.ServiceNotInstalledText;
    public string L_ServiceRemoving => Strings.ServiceRemoving;
    public string L_ServiceRunningText => Strings.ServiceRunningText;
    public string L_ServiceStatusLabel => Strings.ServiceStatusLabel;
    public string L_ServiceStoppedText => Strings.ServiceStoppedText;
    public string L_SettingsAutosaved => Strings.SettingsAutosaved;
    public string L_ShowLogs => Strings.ShowLogs;
    public string L_SmpActiveThrough => Strings.SmpActiveThrough;
    public string L_SmpAdvCardSubtitle => Strings.SmpAdvCardSubtitle;
    public string L_SmpAdvCardTitle => Strings.SmpAdvCardTitle;
    public string L_SmpAdvancedHint => Strings.SmpAdvancedHint;
    public string L_SmpAdvancedLink => Strings.SmpAdvancedLink;
    public string L_SmpAutostartLabel => Strings.SmpAutostartLabel;
    public string L_SmpCfgCustom => Strings.SmpCfgCustom;
    public string L_SmpCfgFull => Strings.SmpCfgFull;
    public string L_SmpCfgManual => Strings.SmpCfgManual;
    public string L_SmpCfgSplit => Strings.SmpCfgSplit;
    public string L_SmpCfgSubscribe => Strings.SmpCfgSubscribe;
    public string L_SmpChangeConfig => Strings.SmpChangeConfig;
    public string L_SmpConfigRowLabel => Strings.SmpConfigRowLabel;
    public string L_SmpConnectedTitle => Strings.SmpConnectedTitle;
    public string L_SmpCtaCancel => Strings.SmpCtaCancel;
    public string L_SmpCtaConnect => Strings.SmpCtaConnect;
    public string L_SmpCtaDisconnect => Strings.SmpCtaDisconnect;
    public string L_SmpDisconnectedTitle => Strings.SmpDisconnectedTitle;
    public string L_SmpFullHint => Strings.SmpFullHint;
    public string L_SmpFullOption => Strings.SmpFullOption;
    public string L_SmpInputHint => Strings.SmpInputHint;
    public string L_SmpInputLabel => Strings.SmpInputLabel;
    public string L_SmpInputWatermark => Strings.SmpInputWatermark;
    public string L_SmpMenuAbout => Strings.SmpMenuAbout;
    public string L_SmpMenuCheckLeaks => Strings.SmpMenuCheckLeaks;
    public string L_SmpMenuCheckUpdates => Strings.SmpMenuCheckUpdates;
    public string L_SmpMenuDiagnosticsSection => Strings.SmpMenuDiagnosticsSection;
    public string L_SmpMenuHealthCheck => Strings.SmpMenuHealthCheck;
    public string L_SmpMenuLanguage => Strings.SmpMenuLanguage;
    public string L_SmpMenuOpenLogs => Strings.SmpMenuOpenLogs;
    public string L_SmpMenuResetConfig => Strings.SmpMenuResetConfig;
    public string L_SmpMenuResetConfirm => Strings.SmpMenuResetConfirm;
    public string L_SmpMenuSafeMode => Strings.SmpMenuSafeMode;
    public string L_SmpMenuSwitchToAdv => Strings.SmpMenuSwitchToAdv;
    public string L_SmpMenuTheme => Strings.SmpMenuTheme;
    public string L_SmpMenuTroubleshootingSection => Strings.SmpMenuTroubleshootingSection;
    public string L_SmpMenuViewSection => Strings.SmpMenuViewSection;
    public string L_SmpPlaceholderBody => Strings.SmpPlaceholderBody;
    public string L_SmpPlaceholderSwitchToAdvanced => Strings.SmpPlaceholderSwitchToAdvanced;
    public string L_SmpPlaceholderTitle => Strings.SmpPlaceholderTitle;
    public string L_SmpSegDark => Strings.SmpSegDark;
    public string L_SmpSegEn => Strings.SmpSegEn;
    public string L_SmpSegLight => Strings.SmpSegLight;
    public string L_SmpSegRu => Strings.SmpSegRu;
    public string L_SmpSplitHint => Strings.SmpSplitHint;
    public string L_SmpSplitOption => Strings.SmpSplitOption;
    public string L_SmpStartVpn => Strings.SmpStartVpn;
    public string L_SmpStatusConnectedNoDetails => Strings.SmpStatusConnectedNoDetails;
    public string L_SmpStatusConnectedVia => Strings.SmpStatusConnectedVia;
    public string L_SmpStatusConnecting => Strings.SmpStatusConnecting;
    public string L_SmpStatusConnectingHint => Strings.SmpStatusConnectingHint;
    public string L_SmpStatusDisconnectedHint => Strings.SmpStatusDisconnectedHint;
    public string L_SmpStatusNotConnected => Strings.SmpStatusNotConnected;
    public string L_SmpStatusProtected => Strings.SmpStatusProtected;
    public string L_SmpStopVpn => Strings.SmpStopVpn;
    public string L_SmpTipAutostart => Strings.SmpTipAutostart;
    public string L_SmpTipFull => Strings.SmpTipFull;
    public string L_SmpTipSplit => Strings.SmpTipSplit;
    public string L_SmpToggleToAdvanced => Strings.SmpToggleToAdvanced;
    public string L_SmpToggleToSimple => Strings.SmpToggleToSimple;
    public string L_SmpToggleTooltip => Strings.SmpToggleTooltip;
    public string L_SmpTunnelModeLabel => Strings.SmpTunnelModeLabel;
    public string L_SplitTunnel => Strings.SplitTunnel;
    public string L_SplitTunnelSubtitle => Strings.SplitTunnelSubtitle;
    public string L_SplitTunnelTitle => Strings.SplitTunnelTitle;
    public string L_StartVPN => Strings.StartVPN;
    public string L_Starting => Strings.Starting;
    public string L_StatusRunning => Strings.StatusRunning;
    public string L_StatusStopped => Strings.StatusStopped;
    public string L_StopVPN => Strings.StopVPN;
    public string L_Stopping => Strings.Stopping;
    public string L_StrictDnsLabel => Strings.StrictDnsLabel;
    public string L_StrictModeHint => Strings.StrictModeHint;
    public string L_StrictModeLabel => Strings.StrictModeLabel;
    public string L_SubUpdatedAt => Strings.SubUpdatedAt;
    public string L_SubscribeMode => Strings.SubscribeMode;
    public string L_SubscriptionNameHint => Strings.SubscriptionNameHint;
    public string L_SubscriptionUrlHint => Strings.SubscriptionUrlHint;
    public string L_SubscriptionsSection => Strings.SubscriptionsSection;
    public string L_SyncButton => Strings.SyncButton;
    public string L_SyncEmpty => Strings.SyncEmpty;
    public string L_Syncing => Strings.Syncing;
    public string L_TabApps => Strings.TabApps;
    public string L_TabFreeConfigs => Strings.TabFreeConfigs;
    public string L_TabNetwork => Strings.TabNetwork;
    public string L_TabServers => Strings.TabServers;
    public string L_TabSettings => Strings.TabSettings;
    public string L_TabTelegram => Strings.TabTelegram;
    public string L_TabTgWsProxy => Strings.TabTgWsProxy;
    public string L_TabZapret => Strings.TabZapret;
    public string L_TcpUdpHint => Strings.TcpUdpHint;
    public string L_TgProxyCopied => Strings.TgProxyCopied;
    public string L_TgProxyCopy => Strings.TgProxyCopy;
    public string L_TgProxyDescription => Strings.TgProxyDescription;
    public string L_TgProxyLink => Strings.TgProxyLink;
    public string L_TgProxyOpenInTelegram => Strings.TgProxyOpenInTelegram;
    public string L_TgProxyPort => Strings.TgProxyPort;
    public string L_TgProxyRegenerate => Strings.TgProxyRegenerate;
    public string L_TgProxySecret => Strings.TgProxySecret;
    public string L_TgProxySetupHint => Strings.TgProxySetupHint;
    public string L_TgProxySetupOnce => Strings.TgProxySetupOnce;
    public string L_TgProxyStart => Strings.TgProxyStart;
    public string L_TgProxyStop => Strings.TgProxyStop;
    public string L_ThemeDark => Strings.ThemeDark;
    public string L_ThemeLight => Strings.ThemeLight;
    public string L_TipBlockAds => Strings.TipBlockAds;
    public string L_TipBypassRu => Strings.TipBypassRu;
    public string L_TipClearAllCache => Strings.TipClearAllCache;
    public string L_TipClearFailed => Strings.TipClearFailed;
    public string L_TipCloseServerDetail => Strings.TipCloseServerDetail;
    public string L_TipDeepVerifyServers => Strings.TipDeepVerifyServers;
    public string L_TipFcFastScan => Strings.TipFcFastScan;
    public string L_TipFcSkipRu => Strings.TipFcSkipRu;
    public string L_TipFcSmartRefresh => Strings.TipFcSmartRefresh;
    public string L_TipIpLeak => Strings.TipIpLeak;
    public string L_TipKeepVerifiedOnly => Strings.TipKeepVerifiedOnly;
    public string L_TipLeakBlockOnFail => Strings.TipLeakBlockOnFail;
    public string L_TipLeakFlushDns => Strings.TipLeakFlushDns;
    public string L_TipLeakForceIpv4 => Strings.TipLeakForceIpv4;
    public string L_TipLeakStrictDns => Strings.TipLeakStrictDns;
    public string L_TipLeakStrictMode => Strings.TipLeakStrictMode;
    public string L_TipOpenFreeConfigLogs => Strings.TipOpenFreeConfigLogs;
    public string L_TipOpenLogs => Strings.TipOpenLogs;
    public string L_TipRefreshSubscription => Strings.TipRefreshSubscription;
    public string L_TipRemoveApp => Strings.TipRemoveApp;
    public string L_TipRemoveCategory => Strings.TipRemoveCategory;
    public string L_TipRemoveSubscription => Strings.TipRemoveSubscription;
    public string L_TipSmpMenuAbout => Strings.TipSmpMenuAbout;
    public string L_TipSmpMenuHealthCheck => Strings.TipSmpMenuHealthCheck;
    public string L_TipSmpMenuResetConfig => Strings.TipSmpMenuResetConfig;
    public string L_TipSmpMenuSafeMode => Strings.TipSmpMenuSafeMode;
    public string L_TipTcpTlsPing => Strings.TipTcpTlsPing;
    public string L_TipTestAllServers => Strings.TipTestAllServers;
    public string L_TipTestTcpTls => Strings.TipTestTcpTls;
    public string L_TipZapretAutoUpdate => Strings.TipZapretAutoUpdate;
    public string L_ToolsSection => Strings.ToolsSection;
    public string L_TrayExit => Strings.TrayExit;
    public string L_TraySettings => Strings.TraySettings;
    public string L_TrayStart => Strings.TrayStart;
    public string L_TrayStop => Strings.TrayStop;
    public string L_UpToDate => Strings.UpToDate;
    public string L_UpdateApplying => Strings.UpdateApplying;
    public string L_UpdateAvailableMessage => Strings.UpdateAvailableMessage;
    public string L_UpdateAvailableShort => Strings.UpdateAvailableShort;
    public string L_UpdateButton => Strings.UpdateButton;
    public string L_UpdateDownloading => Strings.UpdateDownloading;
    public string L_UpdateFailed => Strings.UpdateFailed;
    public string L_UpdateHostsFile => Strings.UpdateHostsFile;
    public string L_UpdateIpSet => Strings.UpdateIpSet;
    public string L_UpdateRestarting => Strings.UpdateRestarting;
    public string L_VlessServers => Strings.VlessServers;
    public string L_WmTgProxyPort => Strings.WmTgProxyPort;
    public string L_WmTgProxySecret => Strings.WmTgProxySecret;
    public string L_WmVlessUri => Strings.WmVlessUri;
    public string L_WmZapretCustomArgs => Strings.WmZapretCustomArgs;
    public string L_ZapretHostsHint => Strings.ZapretHostsHint;
    public string L_ZapretSecAdvanced => Strings.ZapretSecAdvanced;
    public string L_ZapretSecDiagnostics => Strings.ZapretSecDiagnostics;
    public string L_ZapretSecFilters => Strings.ZapretSecFilters;
    public string L_ZapretSecHosts => Strings.ZapretSecHosts;
    public string L_ZapretSecStatus => Strings.ZapretSecStatus;
    public string L_ZapretSecStrategy => Strings.ZapretSecStrategy;
    public string L_ZapretSecUpdates => Strings.ZapretSecUpdates;

    /// <summary>
    /// Broadcasts PropertyChanged for every L_* proxy via reflection.
    /// Runs in ~1ms for 200 properties (faster than allocating a single
    /// MainWindow clone). Also fires for existing Lbl* properties so the
    /// same path refreshes hand-written localized properties.
    /// </summary>
    private void RefreshL10nProxies()
    {
        var t = typeof(MainWindowViewModel);
        foreach (var prop in t.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (prop.Name.StartsWith("L_") || prop.Name.StartsWith("Lbl"))
                OnPropertyChanged(prop.Name);
        }
    }
}
