using VPNRouter.Core.Models;
using VPNRouter.Core.Services;
using VPNRouter.Core.Services.EmergencyChannel;

namespace VPNRouter.Tests;
/// <summary>v2.31.0-r1 (CO-5 audit fix): netsh output parser must NOT match
/// `Description:` lines on localized Windows. Only the FIRST colon-line per
/// blank-separated rule block is treated as the rule name.</summary>
public class FirewallManagerLocalizedNetshTests
{
    [Fact]
    public void DescriptionLine_StartingWithPrefix_DoesNotMatch()
    {
        // Simulated `netsh advfirewall firewall show rule name=all dir=out`
        // output on RU Windows. The user has an UNRELATED rule whose
        // Description happens to start with "VPNRouter_Block_". The previous
        // parser would falsely match it.
        var simulated = @"
Имя правила:                          Allow Some Application
Описание:                             VPNRouter_Block_Discord description leak
Действие:                             Allow

Имя правила:                          VPNRouter_Block_Telegram
Описание:                             Auto-generated by VPNRouter
Действие:                             Block
".Replace("\r\n", "\n");

        // Apply same parser logic as FirewallManager.FindRulesByPrefix:
        // first colon-line per blank-separated block.
        var prefix = "VPNRouter_Block_";
        var matches = new List<string>();
        var inNewBlock = true;
        foreach (var line in simulated.Split('\n'))
        {
            var trimmed = line.Trim();
            if (trimmed.Length == 0) { inNewBlock = true; continue; }
            if (!inNewBlock) continue;
            inNewBlock = false;
            var colonIdx = trimmed.IndexOf(':');
            if (colonIdx < 0) continue;
            var value = trimmed[(colonIdx + 1)..].Trim();
            if (value.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                matches.Add(value);
        }

        // Should match ONLY the second block's "VPNRouter_Block_Telegram" —
        // the first block's Description leak must NOT appear.
        Assert.Single(matches);
        Assert.Equal("VPNRouter_Block_Telegram", matches[0]);
    }

    [Fact]
    public void EnglishLocale_StillMatchesCorrectly()
    {
        // Sanity: the new block-aware parser still works on English Windows.
        var simulated = @"
Rule Name:                            VPNRouter_Block_Discord
Description:                          Auto-generated
Action:                               Block

Rule Name:                            VPNRouter_Block_Browsers
Description:                          Auto-generated
Action:                               Block
".Replace("\r\n", "\n");

        var prefix = "VPNRouter_Block_";
        var matches = new List<string>();
        var inNewBlock = true;
        foreach (var line in simulated.Split('\n'))
        {
            var trimmed = line.Trim();
            if (trimmed.Length == 0) { inNewBlock = true; continue; }
            if (!inNewBlock) continue;
            inNewBlock = false;
            var colonIdx = trimmed.IndexOf(':');
            if (colonIdx < 0) continue;
            var value = trimmed[(colonIdx + 1)..].Trim();
            if (value.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                matches.Add(value);
        }

        Assert.Equal(2, matches.Count);
        Assert.Contains("VPNRouter_Block_Discord", matches);
        Assert.Contains("VPNRouter_Block_Browsers", matches);
    }
}
