using System;
using Android.App;
using Android.Runtime;
using Avalonia;
using Avalonia.Android;

namespace VPNRouter.Android;

/// <summary>
/// Wave 23 (Phase 5, 2026-05-18) — required by Avalonia 12 Android.
///
/// <para>Avalonia 11 worked off the Activity-side generic
/// <c>AvaloniaMainActivity&lt;TApp&gt;</c>: the Activity itself was
/// responsible for spinning up the Avalonia <c>AppBuilder</c> via
/// <c>CreateAppBuilder()</c>. In 12 the generic Activity was retired —
/// only the non-generic <c>AvaloniaMainActivity</c> remains. Instead,
/// the Android <c>Application</c> object is expected to implement
/// <see cref="Avalonia.Android.IAndroidApplication"/>; Avalonia ships
/// <c>AvaloniaAndroidApplication&lt;TApp&gt;</c> as the canonical base
/// class which:</para>
///
/// <list type="number">
///   <item>Invokes <c>OnCreate</c> on the .NET Application,</item>
///   <item>Builds the <c>AppBuilder</c> with <c>UseAndroid()</c>,</item>
///   <item>Stashes the resulting <see cref="Avalonia.Controls.ApplicationLifetimes.IApplicationLifetime"/> on the Application instance,</item>
///   <item>Lets <see cref="AvaloniaMainActivity"/> pick up the lifetime
///         to mount the first view.</item>
/// </list>
///
/// <para>The <c>[Application]</c> attribute below registers this class
/// as the Android-runtime Application (manifest <c>android:name</c>
/// is auto-generated by .NET Android), so <c>Activity.Application</c>
/// returns a <see cref="MainApplication"/> instance which
/// <see cref="AvaloniaMainActivity"/> can cast to
/// <c>IAndroidApplication</c>.</para>
/// </summary>
[Application]
public class MainApplication : AvaloniaAndroidApplication<AndroidApp>
{
    /// <summary>
    /// JNI constructor — invoked by ART when the OS instantiates our
    /// process. Must forward to the base class to wire the Java peer.
    /// </summary>
    protected MainApplication(IntPtr javaReference, JniHandleOwnership transfer)
        : base(javaReference, transfer)
    {
    }

    /// <summary>
    /// Hook to apply our custom AppBuilder tweaks. Mirrors the
    /// <c>WithInterFont()</c> chain that lived in MainActivity's
    /// CustomizeAppBuilder in the 11.3.12 layout.
    /// </summary>
    protected override AppBuilder CustomizeAppBuilder(AppBuilder builder)
    {
        return base.CustomizeAppBuilder(builder)
            .WithInterFont();
    }
}
